### ISSUE TITLE
Find images of cityscapes

### ISSUE THREAD

**Issue by chrisdonofrio** [chrisdonofrio/hotel-project#19]
Dong,

can you find 5 images for these cities? (preferably of the cityscape)-- they'll be inside a folder called img

- San Francisco
- Honolulu
- Los Angeles
- New York
- Miami

**Comment by donghoonkim1226** [comment]
@chrisdonofrio you sure you dont need cityscape pics for every city?

**Comment by donghoonkim1226** [comment]
@chrisdonofrio - added cityscapes for all 10 cities.
