### ISSUE TITLE
Find images of hotels

### ISSUE THREAD

**Issue by chrisdonofrio** [chrisdonofrio/hotel-project#20]
Let's do 10 search results for the following cities-- find images of the hotel exterior for each

- San Francisco
- Honolulu
- Los Angeles
- New York
- Chicago
- Denver
- Austin
- Seattle
- Portland
- Miami

**Comment by donghoonkim1226** [comment]
@chrisdonofrio - added 4 images instead of 1. I think the webpage should at least show 4 images in a carousel.

**Comment by donghoonkim1226** [comment]
@chrisdonofrio instead of portland i have switched it to orlando and instead of Honolulu i switched it Maui. it was just easier to get pictures for them.
